<Project>
  <PropertyGroup>
    <LsRoot Condition="'$(LsRoot)' == ''">$(MSBuildThisFileDirectory)..\LiveSplit</LsRoot>
    <LsSrcPath>$(LsRoot)\src</LsSrcPath>
    <LsLibPath>$(LsRoot)\lib</LsLibPath>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
